name = "gaki"
compatibility_date = "2026-02-04"

pages_build_output_dir = "src"

[vars]
CHANNELS_ACCESS_TOKEN = "kore-is-the-most-anzen-tookun-nari-ne"
POST_ACCESS_TOKEN = "this-wa-mottomo-secure-token-aru-yo"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
